# Generated by Django 4.2 on 2024-06-20 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_officeuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='officeuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
