# Generated by Django 4.2 on 2024-06-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_officeuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('client', 'Клиент')], max_length=10),
        ),
    ]
