# Generated by Django 4.2 on 2024-06-26 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_application_report_alter_officeuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='author_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
