# Generated by Django 4.2 on 2024-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='password',
            field=models.CharField(default='password', max_length=100, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.CharField(default='user', max_length=100, verbose_name='Логин'),
        ),
    ]
