# Generated by Django 4.2 on 2024-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_storage_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='storage_name_from',
            field=models.IntegerField(verbose_name='Номер хранилища начального'),
        ),
        migrations.AlterField(
            model_name='application',
            name='storage_name_to',
            field=models.IntegerField(verbose_name='Номер хранилища конечного'),
        ),
    ]
